config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
   authenticated :user do
    root to: 'odds#index'
  end

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :odds, only: [:show, :index] do
    resources :bets, only: [:create, :destroy, :update]
  end

  post 'incoming_webhooks', to: 'webhooks#incoming'


  get "/dashboard", to: "users#dashboard"
  resources :charges
  resources :subscribers
  get '/cancel_plan', to: "subscribers#cancel_plan"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, omniauth_providers: [:facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :odds
  has_many :bets, dependent: :destroy;

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end
    return user
  end

  def completed_bets
    bets.joins(:match).where('matches.status = ?', 'FINISHED').order(:created_at)
  end

  # TOMMY'S METHODS ###########
  def wins
    bets.select &:won?
  end

  def losses
    bets.select &:lost?
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?

    user.stripe_customer = Stripe::Customer.create( email: user.email )

    user.stripe_subscription = Stripe::Subscription.create(
      customer: user.stripe_customer['id'],
      items: [
        {
          plan: 'basic-plan-databall',
        },
      ],
      trial_end: (Time.now + 14.days).to_i,
    )

    user.save


    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end




end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    resource.stripe_customer = Stripe::Customer.create( email: resource.email )

    resource.stripe_subscription = Stripe::Subscription.create(
      customer: resource.stripe_customer['id'],
      items: [
        {
          plan: 'basic-plan-databall',
        },
      ],
      trial_end: (Time.now + 14.days).to_i,
    )

    resource.save
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  def after_sign_up_path_for(resource)
    '/charges/new' # Or :prefix_to_your_route
  end

   def after_inactive_sign_up_path_for(resource)
    root_path # Or :prefix_to_your_route
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    redirect_to new_charge_path if current_user.access == false
    @user = current_user

    @bet_dates = current_user.completed_bets.pluck(:created_at).map{ |d| d.strftime('%d %b %Y') }

    @bet_color = []
    @user.bets.each do |bet|
      if bet.status == "won"
        @bet_color << "#50FFB1"
      elsif bet.status == "lost"
        @bet_color << "#EA526F"
      else
        @bet_color << "#959595"
      end
    end

    @cumulative_total = []
    @user.bets.each do |bet|
      previous_total = @cumulative_total.last || 0
      @cumulative_total << (if bet.won?
        previous_total + bet.stake * bet.odd.odds
      elsif bet.lost?
        previous_total - bet.stake
      else
        previous_total
      end)
    end

    @completed_bet_returns = []
    @completed_bet_status = []
    @completed_bet_color = []
    @user.completed_bets.each do |bet|
      if bet.won?
        @completed_bet_returns << bet.stake * bet.odd.odds
        @completed_bet_status << "won"
        @completed_bet_color << "#50FFB1"
      elsif bet.lost?
        @completed_bet_returns << - bet.stake
        @completed_bet_status << "lost"
        @completed_bet_color << "#EA526F"
      end
    end

    @bet_returns = current_user.completed_bets.map do |bet|
      if bet.won?
        bet.stake * bet.odd.odds
      elsif bet.pending?
        0
      else
        - bet.stake
      end
    end

    @profits = @bet_dates.zip @bet_returns


    # TOMMY'S CODE
    @bets = @user.bets.order(created_at: :desc)
    @wins = @user.wins
    @losses = @user.losses

    # CALCULATE TOTAL MONEY BET
    _stakes = []
    @bets.each { |bet| _stakes << bet.stake }
    @total_stake = _stakes.reduce(0, :+)

    # CACLULATE PROFIT/LOSS
    _winnings = []
    @wins.each { |bet| _winnings << ((bet.stake * bet.odd.odds) - bet.stake) }
    winning_profit = _winnings.reduce(0, :+)
    _losses = []
    @losses.each { |bet| _losses << bet.stake}
    losing_total = _losses.reduce(0, :+)
    @total_profit = (winning_profit - losing_total).round(2)

    # END OF DASHBOARD
  end
  #########
end

app/views/users/_adrian_js_charts.html.erb
<!-- LINE CHART -->
<!--   <canvas id="lineChart" style="background-color: transparent;"></canvas>
    <script>
        var ctx = document.getElementById("lineChart");
        var lineChart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: <%# raw @bet_dates %>,
            datasets: [{
                data: <%# raw @bet_returns %>,
                label: "Your profit",
                backgroundColor: "rgba(0, 21, 33, 0.7)",
                borderColor: "rgba(80, 255, 177, 1)",
                borderWidth: 1,
                borderCapStyle: 'butt',
                fill: false
              }
            ]
          },
          options: {
            title: {
              display: true,
              text: 'Your performance',
              fontColor: 'rgba(0,0,0,0)',
              fontStyle: 'light'
            }
          }
        });
    </script> -->

<!-- BARCHART -->
<!-- <h1>nooooo one_hundread_branches</h1> -->
      <canvas id="bar-chart"></canvas>
      <script>
        new Chart(document.getElementById("bar-chart"), {
        type: 'bar',
        data: {
          labels: <%# raw @bet_dates %>,
          datasets: [
            {
              label: "Performance",
              backgroundColor: <%# raw @bet_color %>,
              data: <%# raw @bet_returns %>
            }
          ]
        },
        options: {
          legend: { display: false },
          title: {
            display: true,
            text: 'Bar Chart'
                }
              }
          });
      </script>

app/views/users/_dashboard_grid1.html.erb
<div class="dashboard_grid1">
    <!-- MAIN CHART -->
    <div class="main-chart">
      <canvas id="cumulativeOutcome" style="background-color: transparent;"></canvas>
      <%= content_for :after_js do %>
      <script>
          var inputs = {
            min: -100,
            max: 100,
            count: 8,
            decimals: 2,
            continuity: 1
          };
          var canvas_element = document.getElementById("cumulativeOutcome");
          // canvas_element.height = 75;
          var lineChart = new Chart(canvas_element, {
            type: 'line',
            data: {
              labels: <%= raw @bet_dates %>,
              datasets: [{
                  data: <%= raw @cumulative_total %>,
                  label: "Total Profit",
                  backgroundColor: "rgba(0, 21, 33, 0.7)",
                  borderColor: "rgba(80, 255, 177, 1)",
                  borderWidth: 1,
                  borderCapStyle: 'butt',
                  fill: true
                }
              ]
            },
            options: {
              responsive: true,
              maintainAspectRatio: false,
              title: {
                display: true,
                text: 'Cumulative Profit',
                fontColor: 'rgba(0,0,0,0)',
                fontStyle: 'light'
              },
              hover: {
                intersect: true,
                animationDuration: 400,
              },
              scales: {
                xAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'Month'
                    }
                }],
                yAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'Value'
                    }
                }]
            }
          }});
      </script>
      <% end %>
    </div>
    <!-- BAR CHART -->
    <div class="bar-chart">
      <canvas id="bar-chart"></canvas>
      <%= content_for :after_js do %>
      <script>
        new Chart(document.getElementById("bar-chart"), {
        type: 'bar',
        data: {
          labels: <%= raw @bet_dates %>,
          datasets: [
            {
              label: <%= @completed_bet_status = [] %>,
              backgroundColor: <%= raw @completed_bet_color %>,
              data: <%= raw @completed_bet_returns %>
            }
          ]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          legend: { display: false },
          title: {
            display: false,
            text: 'Bar Chart'
                }
              }
          });
      </script>
      <% end %>
    </div>
    <!-- EXTRA INFO -->
    <div class="wins other-information text-center">
        <h4>Wins</h4>
        <h5 class="text-green text-center other-information-text"><%= @wins.count %></h5>
    </div>
    <div class="losses other-information text-center">
        <h4>Losses</h4>
        <h5 class="text-red text-center other-information-text"><%= @losses.count %></h5>
    </div>
    <div class="total-profit other-information">
        <h4>Profit</h4>
        <h5><%= @total_profit > 0 ? "" : "-" %>£ <span class="<%= @total_profit > 0 ? "text-green" : "text-red" %>"><%= @total_profit.abs %></span></h5>
    </div>
    <div class="total-bet other-information">
      <h4 class="text-center">Invested</h4>
      <h5 class="text-center other-information-text">£ <%= @total_stake %></h5>
    </div>
</div>

app/views/users/_dashboard_grid2.html.erb
<div class="dashboard_grid2">
      <h3>Bets you have made:</h3>
    <div class="filter-bar">
      <%= link_to 'All', "", class: "dashboard-tab all" %>
      <%= link_to 'Won', "", class: "dashboard-tab", "data-target" => ".won" %>
      <%= link_to 'Lost', "", class: "dashboard-tab", "id" => "lost-click", "data-target" => ".lost" %>
      <%= link_to 'Pending', "", class: "dashboard-tab", "data-target" => ".pending" %>
    </div>
      <div class="headers">
        <div id="header-empty-space">

        </div>
        <div id="dash-headers-box">
          <h5 id="outcome-head">Outcome</h5>
          <div id="stupid-dumb-div">
            <h5 id="stake-head">Stake</h5>
            <h5 id="result-head">Score</h5>
          </div>
          <h5 id="bet-result-head">Bet</h5>
          <h5 id="bookmaker-head">Bookmaker</h5>
        </div>
      </div>
    <div class="odds-container2">
      <% @bets.each do |bet| %>
        <%= render "shared/dashboard_card", bet: bet %>
      <% end %>
    </div>
</div>

app/views/users/_dashboard_grid3.html.erb
<div class="dashboard_grid3">
  <!-- <div class="main-chart2"> -->
    <!-- <canvas id="lineChart" style="background-color: transparent;"></canvas>
    <script>
        var ctx = document.getElementById("lineChart");
        var lineChart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: <%# raw @bet_dates %>,
            datasets: [{
                data: <%# raw @bet_returns %>,
                label: "Your profit",
                backgroundColor: "rgba(0, 21, 33, 0.7)",
                borderColor: "rgba(80, 255, 177, 1)",
                borderWidth: 1,
                borderCapStyle: 'butt',
                fill: false
              }
            ]
          },
          options: {
              responsive: true,
              maintainAspectRatio: false,
              title: {
                display: true,
                text: 'Cumulative Profit',
                fontColor: 'rgba(0,0,0,0)',
                fontStyle: 'light'
              },
              hover: {
                intersect: true,
                animationDuration: 400,
              },
              scales: {
                xAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'Month'
                    }
                }],
                yAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'Value'
                    }
                }]
              }
            });
    </script> -->
  <!-- </div> -->
  <div class="odds-container2">
      <h3>Bets you have made:</h3>
      <% @bets.each do |bet| %>
        <%= render "shared/dashboard_card", bet: bet %>
      <% end %>
  </div>
  <div class="cancel-subscription container">
      <button type="button" class="btn btn-default fuckoff"><%= link_to "Cancel subscription",cancel_plan_path %></button>
  </div>
</div>

app/views/users/_finished_body.html.erb
<% if bet.won? %>
  <div class="hover-box">
      <h6 class="">winnings</h6>
      <p>£ <span class="won"><%= bet.winnings %></span></p>
  </div>
<% else %>
    <div class="hover-box">
      <h6 class="">lost</h6>
      <p>£ <span class="lost"><%= bet.stake %></span></p>
  </div>
<% end %>

app/views/users/dashboard.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<%= javascript_include_tag "dashboard" %>

<div class="dashboard-container">
      <%= render "shared/dashboard-navigation" %>
      <div class="tab-content">
      <!-- GRID 1 -->
        <div role="tabpanel" class="tab-pane active" id="main-grid">
            <%= render "dashboard_grid1" %>
        </div>
      <!-- GRID 2 -->
        <div role="tabpanel" class="tab-pane" id="second-grid">
            <%= render "dashboard_grid2" %>
        </div>
      <!-- GRID 3 -->
        <div role="tabpanel" class="tab-pane" id="third-grid">
            <%= render "dashboard_grid3" %>
        </div>
      </div>
<!-- Dashboard_Container -->
</div>

<% content_for(:after_js) do %>
<% end %>