config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
   authenticated :user do
    root to: 'odds#index'
  end

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :odds, only: [:show, :index] do
    resources :bets, only: [:create, :destroy, :update]
  end

  post 'incoming_webhooks', to: 'webhooks#incoming'


  get "/dashboard", to: "users#dashboard"
  resources :charges
  resources :subscribers
  get '/cancel_plan', to: "subscribers#cancel_plan"
end

app/views/shared/_bet_modal.html.erb
<div id="makeBet-<%= odd.id %>" class="bet-modal modal fade" role="dialog">
  <div class="modal-dialog modal-sm">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close modal-close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Add this bet to your profile:</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [odd, @bet], remote: true do |f| %>
          <%= f.label 'Stake:' %>
          <%= f.input :stake, label: false, :class => "stake-input", input_html: { min: '0', step: 'any' } do %>
          <%= content_tag :span, "£", class: "add-on" %>
          <%= f.number_field :stake %>
          <%= f.submit 'Add Bet', :class => "modal-btn", input_html: { class: "align-right" } %>
          <% end %>
        <% end %>
      </div>
      <div class="modal-bookie">
        <div class="bookie-message">
          Click to go to:
        </div>
        <div class="bookie-link text-center">
          <a href="<%= odd.bookmaker.url %>" target="_blank">
            <%= cl_image_tag("#{odd.bookmaker.logo}.png", :radius=>15, :width=>80, :crop=>"scale")  %>
          </a>
        </div>
      </div>
      <div class="modal-profile-button text-center">
        <a href="/dashboard" class="btn">Go to profile</a>
      </div>
    </div>

  </div>
</div>

app/views/shared/_button.html.erb
  <div class="svg-wrapper">
    <svg height="60" width="320" xmlns="http://www.w3.org/2000/svg">
      <rect class="shape" height="60" width="320" />
    </svg>
     <div class="text">HOVER</div>
  </div>

app/views/shared/_card.html.erb
<%= link_to odd_path(odd.id) do %>
  <div class="index-card" data-target="#new_match">
    <div class="rating">
      <span><%= count %></span>
    </div>

    <div class="card-teams flex-item">
      <div class="team <%= "winning-team" if true %>">
        <% if odd.match.home_team.logo %>
          <% photo = odd.match.home_team.logo %>
        <% else %>
          <% photo = "logo.png" %>
        <% end %>
        <div class="icons">
          <%= image_tag photo, class:"team-logo" %>
          <div style="margin-left: 20px;">
          <% if odd.outcome == "Draw" %>
            <span class="draw-underline"><%= odd.match.home_team.name %></span>
          <% elsif odd.outcome == "Home" %>
            <span class="win-underline"><%= odd.match.home_team.name %></span>
          <% else %>
            <span class=""><%= odd.match.home_team.name %></span>
          <% end %>
          </div>
        </div>
      </div>
      <div class="team <%= "winning-team" if false %>">
        <% if odd.match.away_team.logo %>
          <% photo = odd.match.away_team.logo %>
        <% else %>
          <% photo = "logo.png" %>
        <% end %>
        <div class="icons">
          <%= image_tag photo, class:"team-logo" %>
          <div style="margin-left: 20px;">
          <% if odd.outcome == "Draw" %>
            <span class="draw-underline"><%= odd.match.away_team.name %></span>
          <% elsif odd.outcome == "Away" %>
            <span class="win-underline"><%= odd.match.away_team.name %></span>
          <% else %>
            <span class=""><%= odd.match.away_team.name %></span>
          <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="card-middle">
      <div class="match-date">
        <h4><%= odd.match.match_date.strftime('%e/%m/%y') %></h4>
      </div>
      <div class="outcome">
        <h3><%= odd.outcome.upcase %> <%# odd.outcome.upcase == "DRAW" ? "" : "win" %></h3>
      </div>

      <div class="bookmaker">
        <% if odd.bookmaker %>
          <%= cl_image_tag("#{odd.bookmaker.logo}.png", :radius=>15, :width=>50, :crop=>"scale")  %>
        <% else %>
          <%= image_tag 'logo.png' %>
        <% end %>
        <span class="new_match active" id="decimal_odd" ><%= odd.odds %></span>
        <span class="new_match" id="fractional_odd" ><%= odd.frac_odd %></span>
      </div>
    </div>

    <div class="card-end">
      <% rating = odd.mapped_rating.to_f %>
      <% hex = "" %>
      <% if (rating <= 100) && (rating > 98) %>
        <% hex = "yellowbright.png" %>
      <% elsif (rating <= 98) && (rating > 96) %>
        <% hex = "yellow1.png" %>
      <% elsif (rating <= 96) && (rating > 94) %>
        <% hex = "fucking-bright-green.png" %>
      <% elsif (rating <= 94) && (rating > 92) %>
      <% hex = "very-light-green.png" %>
      <% elsif (rating <= 92) && (rating > 90) %>
      <% hex = "light-green.png" %>
      <% elsif (rating <= 90) && (rating > 88) %>
      <% hex = "mid-green.png" %>
      <% elsif (rating <= 88) && (rating > 86) %>
      <% hex = "dark-green.png" %>
      <% elsif (rating <= 86) && (rating > 84) %>
      <% hex = "light-blue.png" %>
      <% elsif (rating <= 84) && (rating > 82) %>
      <% hex = "mid-blue.png" %>
      <% elsif (rating <= 82) && (rating > 80) %>
      <% hex = "dark-blue.png" %>
      <% elsif (rating <= 80) && (rating > 78) %>
      <% hex = "lightpurp.png" %>
      <% elsif  (rating <= 78) && (rating > 76) %>
      <% hex = "light-purple.png" %>
      <% elsif  (rating <= 76) && (rating > 74) %>
      <% hex = "mid-purple.png" %>
      <% elsif  (rating <= 74) && (rating > 72) %>
      <% hex = "dark-purple.png" %>
      <% elsif  (rating <= 72) && (rating >= 70) %>
      <% hex = "dark-purple.png" %>
      <% else %>
      <% hex = "dark-purple.png" %>

        
        
      <% end %>

      <% if rating > 88 %>
        <% black_color = "black-span" %>
      <% end %>

      <div class="hexagon" style="background-image: url(<%= image_path hex %>)">
          <span class="match-rating <%= black_color %>"> <%= rating %></span>
      </div>
    </div>
</div>

<% end %>

app/views/shared/_dashboard-navigation.html.erb
<div class="dashboard-navigation">
  <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active">
        <a href="#main-grid" aria-controls="main-grid" role="tab" data-toggle="tab">
          <i class="fa fa-home" aria-hidden="true"></i>
        </a>
      </li>
      <li role="presentation">
        <a href="#second-grid" aria-controls="second-grid" role="tab" data-toggle="tab">
          <i class="fa fa-bars" aria-hidden="true"></i>
        </a>
      </li>
      <li role="presentation">
        <a href="#third-grid" aria-controls="third-grid" role="tab" data-toggle="tab">
          <i class="fa fa-cog" aria-hidden="true"></i>
        </a>
      </li>
  </ul>
</div>

app/views/shared/_dashboard_card.html.erb
<div class="message <%= bet.won? ? 'won' : nil %>"></div>



<% dashboard_card_color = nil %>

  <% if bet.status == "pending" %>
    <%  dashboard_card_color = "#959595" %>
  <% elsif bet.status == "won" %>
    <% dashboard_card_color = "#50FFB1" %>
  <% elsif bet.status == "lost" %>
    <% dashboard_card_color = "#EA526F" %>

<% end %>




<div class="message active <%= bet.status %>" style="border:2px solid <%= "#{dashboard_card_color}" %>; height: 60px;">
  <div class="message-body cards-team">
        <div class="team home-team">
          <%= image_tag bet.match.home_team.logo ? bet.match.home_team.logo : 'logo.png', class:"team-avatar" %>
          <% if bet.match.outcome == "Draw" %>
            <span class="draw-underline"><%= bet.match.home_team.name %></span>
          <% elsif bet.match.outcome == "Home" %>
            <span class="win-underline"><%= bet.match.home_team.name %></span>
          <% else %>
            <span><%= bet.match.home_team.name %></span>
          <% end %>
        </div>
          <span class="vs-card">VS</span>
          <div class="team-right">
          <div class="team away-team">
            <%= image_tag bet.match.away_team.logo ? bet.match.away_team.logo : 'logo.png', class:"team-avatar" %>
            <% if bet.match.outcome == "Draw" %>
              <span class="draw-underline"><%= bet.match.away_team.name %></span>
            <% elsif bet.match.outcome == "Away" %>
              <span class="win-underline"><%= bet.match.away_team.name %></span>
            <% else %>
              <span><%= bet.match.away_team.name %></span>
            <% end %>
          </div>
          </div>
  </div>

  <div class="message-body outcome">
    <h2 class="home-away-draw"> <%= bet.odd.outcome %> </h2>
  </div>

  <div class="test-width">


  <div class="message-body stake">
      <%= bet.stake %>
  </div>

  <div class="message-body score">
    <% if bet.status == "won" || bet.status == "lost" %>
    <div class="team home-team">
      <%= bet.match.goals_home_team %>
    </div>
    <span> : </span>
    <div class="team away-team">
      <%= bet.match.goals_away_team %>
    </div>
    <% end %>
  </div>


<div class="message-body bet-outcome" id="stake">
    <% if bet.odd.match.status == "FINISHED" %>
      <%= render 'users/finished_body', bet: bet %>
    <% else %>
      <%= render 'users/pending_body', bet: bet %>
    <% end %>
</div>


<div class="bookmaker-dashboard">
  <div class="avatar-container">
    <% creator = bet.odd.bookmaker %>
    <%= cl_image_tag("#{creator.logo}.png", :radius=>15, :width=>50, :crop=>"scale")  %>
  </div>
  <div class="bookmaker-odds">
    <%= bet.odd.odds %>
  </div>
</div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://twitter.com/lewagonlondon"><i class="fa fa-twitter"></i></a>
    <a href="https://www.linkedin.com/school/5046700/"><i class="fa fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_hexagon.html.erb
<div class="hexagon_2"></div>

app/views/shared/_hexagonal.html.erb
<div class="hexagonal">0.8</div>

app/views/shared/_hover_button.html.erb
<div class="svg-wrapper">
  <svg height="60" width="320" xmlns="http://www.w3.org/2000/svg">
    <rect class="shape" height="60" width="320" />
  </svg>
  <%= link_to "#", "data-toggle" => "modal", "data-target" => "#makeBet-#{odd.id}" do %>
  <div class="text">PLACE BET</div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <div class="flex-logo">
    <%= image_tag "logo.png" %> <!-- OR "logo-navbar.png" -->
    <h3 id="company-name">DataBall</h3>
  </div>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Odds", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Profile", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%# link_to "News", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%# link_to "About", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <% avatar_url = current_user.facebook_picture_url || "logo.png" %>
          <div class="avatar dropdown-toggle" style="background-image: url(<%= image_path avatar_url %>);" id="navbar-wagon-menu" data-toggle="dropdown">

          </div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <a class="navbar-wagon-item navbar-wagon-link" data-toggle="modal" data-target="#upModal">Sign up</a>
      <a class="navbar-wagon-item navbar-wagon-link" data-toggle="modal" data-target="#myModal" id="login-btn">Login</a>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="<%= odds_path %>">Home</a></li>
        <li><a href="<%= dashboard_path %>">Profile</a></li>
        <!-- <li><a href="#">Other one</a></li> -->
      </ul>
    </div>
  </div>
</div>

<div id="myModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-container">
        <div class="row">
          <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <div class="modal-body">
              <h2>Log in</h2>

              <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                <div class="form-inputs">
                  <%= f.input :email, required: false, autofocus: true %>
                  <%= f.input :password, required: false %>
                  <div class="remember-me">

                  <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
                </div>

                <div class="form-actions">
                  <%= f.button :submit, "Log in" %>
                </div>
              </div>
              <hr>
              <% end %>
                <hr>
              <% if devise_mapping.registerable? && controller_name != 'registrations' %>
                <div class="sign-up-link">
                <%= link_to "Sign up", new_registration_path(resource_name) %><br />
                </div>

              <% end %>
              <%= render "devise/shared/links" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="upModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-container">
        <div class="row">
          <div class="col-xs-12 col-sm-8 col-sm-offset-2">
            <div class="modal-body">

              <h2>Sign up</h2>

              <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                <%= f.error_notification %>

                <div class="form-inputs">
                  <%= f.input :email, required: true, autofocus: true %>
                  <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
                  <%= f.input :password_confirmation, required: true %>
                </div>

                <div class="form-actions", style="margin-bottom: 20px;">
                  <%= f.button :submit, "Sign up" %>
                </div>
                <% end %>
                <hr>
              <hr>
              <%= render "devise/shared/links" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_user-grid.html.erb
<div class="user-grid">
  <div class="row">
    <div class="col-xs-6 col-sm-6 col-sm-offset-7">
      <div class="user-info">
        <% dashboard_picture = @user.facebook_picture_url%>
        <%= image_tag dashboard_picture, class:'dashboard-avatar' %>
        <% user_info = @user.email%>
        <%= user_info %>
      </div>
    </div>
  </div>
</div>