config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
   authenticated :user do
    root to: 'odds#index'
  end

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :odds, only: [:show, :index] do
    resources :bets, only: [:create, :destroy, :update]
  end

  post 'incoming_webhooks', to: 'webhooks#incoming'


  get "/dashboard", to: "users#dashboard"
  resources :charges
  resources :subscribers
  get '/cancel_plan', to: "subscribers#cancel_plan"
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 1000

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'gbp'
    )
    current_user.update(access: true)
    redirect_to root_path
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>£10.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>

<div class="banner banner-card-payment-page">
  <div class="banner-hex">
    <div class="fuckbutton">
      <div class="charge-new">
        <div class="charge-logo">
          <%= image_tag "logo.png",class:"charge-avatar" %>
          <span>DataBall</span>
        </div>
        <div class="money-shit">
          <h4>1 x £ 5 per month</h4>
          <p>2 week trial period<p>
        </div>

        <div class="more-money-shit">
          <h4>£  5.00</h4>
          <p>£ <span style="color: rgba(80, 255, 177, 1);">-5.00</span></p>
        </div>
        <div class="cancel">

        <span style="font-size: 12px;">After the trial period ends you will be charged for £ 5</span><br>
        <span style="font-size: 12px;">You can always cancel your subscription in the <%= link_to "Profile", dashboard_path  %></span>
        </div>
      </div>
    </div>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-description="A month's subscription"
      data-amount="1000"
      data-locale="auto"
      data-label="Subscribe now">
      </script>
  </div>
</div>
    <% end %>